version: '3.8'

services:
  webhook-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_URL=${OPENSEARCH_URL:-http://opensearch:9200}
      - OPENSEARCH_ADMIN_PW=${OPENSEARCH_ADMIN_PW}
      - OPENSEARCH_USER=${OPENSEARCH_USER:-admin}
      - OPENSEARCH_INDEX=${OPENSEARCH_INDEX:-ingested_code_index}
      - OPENSEARCH_TEXT_FIELD=${OPENSEARCH_TEXT_FIELD:-text}
      - OPENSEARCH_VECTOR_FIELD=${OPENSEARCH_VECTOR_FIELD:-vector_field}
      - OPENSEARCH_BULK_SIZE=${OPENSEARCH_BULK_SIZE:-500}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-amazon.titan-embed-text-v2:0}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CHUNKER_MAX_CHARS=${CHUNKER_MAX_CHARS:-1500}
      - CHUNKER_COALESCE=${CHUNKER_COALESCE:-200}
      - GENERATE_AI_DESCRIPTIONS=${GENERATE_AI_DESCRIPTIONS:-True}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHUNK_DESC_PROVIDER=${CHUNK_DESC_PROVIDER:-openai}
      - PORT=8000
    restart: unless-stopped